# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  APPLICATION_NAME: gurl

tasks:
  build:
    cmds:
      - go build -o bin/{{.APPLICATION_NAME}}
    sources:
      - "**/*.go"
    generates:
      - bin/{{.APPLICATION_NAME}}
    watch: true
